# 在 controllers.yaml 中新增：
panda_group_effort_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
